# Версия docker-compose
# В dev используем подлкючение каталогов хоста в папки докера для оперативного отображения изменений в коде
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx-${ENV_TYPE}
            args:
               - ENV_TYPE=${ENV_TYPE}
        image: fe-nginx-${ENV_TYPE}
        # маршрутизируем порты
        ports:
            - "${ENV_FE_PORT}:80"
        #   - "443:443"
        container_name: fe-nginx-${ENV_TYPE}
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
        # монтируем директорию с конфигурацией хоста
            - ./hosts:/etc/nginx/conf.d
        # монтируем директорию с проектом
            - ./app_js:/var/www/fe