# Версия docker-compose
# В prod используем именованные тома, т.к. код менять не собираемся
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx-${ENV_TYPE}
            args:
                - ENV_TYPE=${ENV_TYPE}
        image: fe-nginx-${ENV_TYPE}
        # маршрутизируем порты
        ports:
            - "${ENV_FE_PORT}:80"
        container_name: fe-nginx-${ENV_TYPE}