#!/bin/bash -
#Building project for different environments

if [ $# -eq 1 ]
then
    echo "Trying to deploy application for $1 environment"
    case "$1" in
        "dev"|"prod")
	    echo "Checking code with SonarCloud"
	    sonar-scanner \
	      -Dsonar.organization=as-cicd-task \
	      -Dsonar.projectKey=cicd-task \
	      -Dsonar.sources=. \
	      -Dsonar.host.url=https://sonarcloud.io -Dsonar.exclusions=**/jquery.js
            echo "Building infrastructure for $1"
	    pushd terraform
		terraform init
		terraform apply -auto-approve || { echo "Error creating infrastructure!"; exit 1; }
	    popd
	    echo "Building backend containers for $1"
	    pushd backend
		./build-back-k8s $1 || { echo "Error building backend!"; exit 1; }
		echo "Pushing backend containers for $1 into ACR"
		./cloud-back-push $1 || { echo "Error uploading backend!"; exit 1; }
        	if [ $1 = "dev" ]
        	then
		./upload-back || { echo "Error uploading backend sources for $1!"; exit 1; }
		fi;
	    popd
	    echo "Building frontend containers for $1"
	    pushd frontend
		./build-front-k8s $1 || { echo "Error building frontend!"; exit 1; }
		echo "Pushing frontend containers for $1 into ACR"
		./cloud-front-push $1 || { echo "Error uploading frontend!"; exit 1; }
        	if [ $1 = "dev" ]
        	then
		./upload-front || { echo "Error uploading frontend sources for $1!"; exit 1; }
		fi;
	    popd
	    echo "Setting up kubernetes for $1"
	    pushd k8s
		./k8start $1 || { echo "Error setting up k8s!"; exit 1; }
	    popd
	    ;;
        *) 
	    echo "Wrong parameter '$1'"
        echo "Usage: start-all 'build-type'"
	echo "where build-type = prod or dev"
	    ;;
    esac
else
        echo "Usage: start-all 'build-type'"
	echo "where build-type = prod or dev"
fi;
