#!/bin/bash -
#Building project for different environments

if [ $# -eq 1 ]
then
    echo "Trying to deploy application for $1 environment"
    case "$1" in
        "prod")
            echo "Building infrastructure for $1"
	    pushd terraform
	    terraform init
	    terraform apply -auto-approve
	    popd
	    echo "Building backend containers for $1"
	    pushd backend
	    ./build-back $1
	    echo "Pushing backend containers for $1 into ARC"
	    ./cloud-back-push $1
	    popd
	    echo "Building frontend containers for $1"
	    pushd frontend
	    ./build-front $1
	    echo "Pushing frontend containers for $1 into ARC"
	    ./cloud-front-push $1
	    popd
	    echo "Setting up kubernetes for $1"
	    pushd k8s
	    export KUBECONFIG=./azurek8s
		pushd ../terraform
		echo "$(terraform output -raw kube_config)" > ../k8s/azurek8s
		popd
	    kubectl apply -f frontend.yaml
	    kubectl apply -f backend.yaml
	    kubectl apply -f ingress.yaml
#	    kubectl get all --all-namespaces
	    echo "============================================================"
	    echo "Use link http://"$(kubectl -n kube-system get svc addon-http-application-routing-nginx-ingress --output jsonpath='{.status.loadBalancer.ingress[0].ip}')" to access web application"
	    echo "============================================================"
	    popd
	    ;;
        *) 
	    echo "Wrong parameter '$1'"
        echo "Usage: start-all 'build-type'"
	echo "where build-type = prod or prod"
	    ;;
    esac
else
        echo "Usage: start-all 'build-type'"
	echo "where build-type = prod or prod"
fi;
