#!/bin/bash -
#Building project for different environments

if [ $# -eq 1 ]
then
    echo "Trying to cleanup after deployment for $1 environment"
    case "$1" in
        "dev"|"prod")
	    echo "Removing backend containers for $1"
	    pushd backend
		./stop-back $1
	    popd
	    echo "Removing frontend containers for $1"
	    pushd frontend
		./stop-front $1
	    popd
	    pushd k8s
	    echo "Removing application from cluster for $1"
		./k8stop $1
		rm azurek8s
	    popd
            echo "Destroying infrastructure for $1"
	    pushd terraform
		terraform init
		terraform destroy -auto-approve
	    popd
	    echo "============================================================"
	    echo "Application and infrastructure removed"
	    echo "============================================================"
	    ;;
        *) 
	    echo "Wrong parameter '$1'"
        echo "Usage: stop-all 'build-type'"
	echo "where build-type = prod or prod"
	    ;;
    esac
else
        echo "Usage: stop-all 'build-type'"
	echo "where build-type = prod or prod"
fi;
