#!/bin/bash -
#Building project for k8s cluster (configMap and secrets env variables setup)

if [ $# -eq 1 ]
then
    echo "Trying to build application for $1 environment"
    case "$1" in
        "dev"|"prod")
            echo "Building $1"
	    docker build -f ./Dockerfile-nginx -t be-nginx-$1:latest .
	    docker build -f ./Dockerfile-php --build-arg ENV_TYPE=$1 -t be-php-$1:latest .
	    ;;
        *) 
	    echo "Wrong parameter '$1'"
        echo "Usage: build-back 'build-type'"
	echo "where build-type = dev or prod"
	    ;;
    esac
else
        echo "Usage: build-back 'build-type'"
	echo "where build-type = dev or prod"
fi;
