# Версия docker-compose
# В dev используем подлкючение каталогов хоста в папки докера для оперативного отображения изменений в коде
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:1.21.1
        # маршрутизируем порты
        ports:
            - "80:80"
        #   - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
        # монтируем директорию с конфигурацией хоста
            - ./hosts:/etc/nginx/conf.d
        # монтируем директорию с проектом
            - ./api:/var/www/api
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # собираем PHP из Dockerfile в текущей папке с указанием типа среды dev или prod из файла .env
        build: 
            context: .
            args: 
                - ENV_TYPE=${ENV_TYPE}
        volumes:
            - ./api:/var/www/api