# Версия docker-compose
# В dev используем подлкючение каталогов хоста в папки докера для оперативного отображения изменений в коде
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:1.21.1
        # маршрутизируем порты
        ports:
            - "${ENV_BE_PORT}:80"
        #   - "443:443"
        container_name: be-nginx-${ENV_TYPE}
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
        # монтируем директорию с конфигурацией хоста
            - ./hosts:/etc/nginx/conf.d
        # монтируем директорию с проектом
            - ./api:/var/www/api
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # собираем PHP из Dockerfile в текущей папке с указанием типа среды dev или prod из файла .env
        build: 
            context: .
            dockerfile: Dockerfile-php-${ENV_TYPE}
            args: 
                - ENV_TYPE=${ENV_TYPE}
                - DB_HOST=${DB_HOST}
                - DB_USERNAME=${DB_USERNAME}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_NAME=${DB_NAME}
        container_name: be-php-${ENV_TYPE}
        volumes:
            - ./api:/var/www/api