# Версия docker-compose
# В prod используем именованные тома, т.к. код менять не собираемся
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx-${ENV_TYPE}
        # маршрутизируем порты
        ports:
            - "80:80"
        #   - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
#        volumes:
        # монтируем директорию с конфигурацией хоста
#            - hosts_conf:/etc/nginx/conf.d
        # монтируем директорию с проектом
#            - app:/var/www/api
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # собираем PHP из Dockerfile в текущей папке с указанием типа среды dev или prod из файла .env
        build: 
            context: .
            args: 
                - ENV_TYPE=${ENV_TYPE}
#        volumes:
#            - app:/var/www/api
#volumes:
#    hosts_conf:
#    app: