# Версия docker-compose
# В prod используем именованные тома, т.к. код менять не собираемся
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx-${ENV_TYPE}
            args:
                - ENV_TYPE=${ENV_TYPE}
        # маршрутизируем порты
        ports:
            - "${ENV_BE_PORT}:80"
        #   - "443:443"
        container_name: be-nginx-${ENV_TYPE}
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # собираем PHP из Dockerfile в текущей папке с указанием типа среды dev или prod из файла .env
        build: 
            context: .
            dockerfile: Dockerfile-php-${ENV_TYPE}
            args: 
                - ENV_TYPE=${ENV_TYPE}
        container_name: be-php-${ENV_TYPE}
