#!/bin/bash -
#Create k8s secret for azure file volume mount
pushd ../terraform
echo "$(terraform output -raw kube_config)" > ../k8s/azurek8s
AZF_SECRET=$(terraform output -raw storage_account_secret)
AZF_ACCOUNT=$(terraform output -raw storage_account_name)
popd
export KUBECONFIG=./azurek8s
kubectl create secret generic azure-secret --from-literal=azurestorageaccountname=$AZF_ACCOUNT --from-literal=azurestorageaccountkey=$AZF_SECRET
AZF_SECRET=""
AZF_ACCOUNT=""