bases:
- ../manifests
namespace: prod
images:
- name: ascicdacr.azurecr.io/ascicdacr/fe-nginx
  newName: ascicdacr.azurecr.io/ascicdacr/fe-nginx-prod:${BUILDNUMBER}
- name: ascicdacr.azurecr.io/ascicdacr/be-nginx
  newName: ascicdacr.azurecr.io/ascicdacr/be-nginx-prod:${BUILDNUMBER}
- name: ascicdacr.azurecr.io/ascicdacr/be-php
  newName: ascicdacr.azurecr.io/ascicdacr/be-php-prod:${BUILDNUMBER}
resources:
- hpa.yaml