apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fe-nginx
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: fe-nginx
        image: ascicdacr.azurecr.io/ascicdacr/fe-nginx-dev
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: fe-source
          mountPath: /var/www/fe
        - name: fe-hosts-source
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: fe-source
        azureFile:
            secretName: azure-secret
            shareName: k8s-files/frontend/app_js
            readOnly: true
      - name: fe-hosts-source
        azureFile:
            secretName: azure-secret
            shareName: k8s-files/frontend/hosts
            readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-php
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: be-php
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: be-php
        image: ascicdacr.azurecr.io/ascicdacr/be-php-dev
        ports:
        - containerPort: 9000
          name: php
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
        - name: be-php-source
          mountPath: /var/www/api
      volumes:
      - name: be-php-source
        azureFile:
            secretName: azure-secret
            shareName: k8s-files/backend/api
            readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: be-nginx
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: be-nginx
        image: ascicdacr.azurecr.io/ascicdacr/be-nginx-dev
        ports:
        - containerPort: 80
          name: backend-nginx
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: be-source
          mountPath: /var/www/api
        - name: be-hosts-source
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: be-source
        azureFile:
            secretName: azure-secret
            shareName: k8s-files/backend/api
            readOnly: true
      - name: be-hosts-source
        azureFile:
            secretName: azure-secret
            shareName: k8s-files/backend/hosts
            readOnly: true
