on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ascicdacr.azurecr.io
        username: ${{ secrets.acr_ascicdacr_username }}
        password: ${{ secrets.acr_ascicdacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/frontend/" -f  "frontend/docker-compose-prod.yaml" -t ascicdacr.azurecr.io/ascicdk8s:${{ github.sha }} --label dockerfile-path=frontend/docker-compose-prod.yaml
        docker push ascicdacr.azurecr.io/ascicdk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ascicdk8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep as-cicd-k8sbb5e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace as-cicd-k8sbb5e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: as-cicd-k8sbb5e
        container-registry-url: ascicdacr.azurecr.io
        container-registry-username: ${{ secrets.acr_ascicdacr_username }}
        container-registry-password: ${{ secrets.acr_ascicdacr_password }}
        secret-name: ascicdk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: as-cicd-k8sbb5e
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          ascicdacr.azurecr.io/ascicdk8s:${{ github.sha }}
        imagepullsecrets: |
          ascicdk8sdockerauth
